apiVersion: apps/v1 
kind: Deployment
metadata:
  name: predict-mask-rcnn
  labels:
    app: myimage
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: myimage
  template:
    metadata:
      labels:
        app: myimage
    spec:
      containers:
      - name: myimage
        image: tensorflow/tensorflow:latest-devel-py3
        command: ["/bin/sh", "-c"]
        args:
         - git clone https://git-codecommit.us-east-1.amazonaws.com/v1/repos/object-detection-rcnn-mask;
           cd /object-detection-rcnn-mask/Mask_RCNN;
           cd cocoapi/PythonAPI;
           make;
           make install;
           python setup.py install;
           cd ../..;
           pip install -r requirements.txt;
           python server.py;
        ports:
        - containerPort: 8080