apiVersion: v1
kind: Service
metadata:
  name: predict-mask-rcnn-service
  labels:
    app: myimage
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: myimage
  type: LoadBalancer